// Auto-generated by LibreLane
module heichips25_internal(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input[7:0] ui_in,
  output[7:0] uo_out,
  input[7:0] uio_in,
  output[7:0] uio_out,
  output[7:0] uio_oe,
  input ena,
  input rst_n,
  inout analog_pin0,
  inout analog_pin1,
  inout analog_adc
);
endmodule
